/**
 * Tests for PreviewPanel Component
 *
 * Tests the preview panel component including:
 * - Display of generated content
 * - Character count display and validation
 * - Editable fields
 * - Apply and Cancel functionality
 * - Accessibility features
 *
 * Requirements: 8.1-8.7, 34.1-34.6
 */

import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { PreviewPanel } from '../components/PreviewPanel';
import '@testing-library/jest-dom';

// Mock WordPress packages
jest.mock( '@wordpress/element', () => ( {
	...jest.requireActual( '@wordpress/element' ),
	useState: jest.requireActual( 'react' ).useState,
	useCallback: jest.requireActual( 'react' ).useCallback,
	useRef: jest.requireActual( 'react' ).useRef,
} ) );

jest.mock( '@wordpress/components', () => ( {
	Button: jest
		.requireActual( 'react' )
		.forwardRef(
			(
				{
					children,
					onClick,
					disabled,
					isSecondary,
					isPrimary,
					...props
				},
				ref
			) => (
				<button
					ref={ ref }
					onClick={ onClick }
					disabled={ disabled }
					{ ...props }
				>
					{ children }
				</button>
			)
		),
	TextControl: ( { label, value, onChange, inputId, ...props } ) => (
		<div>
			<label htmlFor={ inputId }>{ label }</label>
			<input
				id={ inputId }
				type="text"
				value={ value }
				onChange={ ( e ) => onChange( e.target.value ) }
				{ ...props }
			/>
		</div>
	),
	TextareaControl: ( {
		label,
		value,
		onChange,
		inputId,
		rows,
		...props
	} ) => (
		<div>
			<label htmlFor={ inputId }>{ label }</label>
			<textarea
				id={ inputId }
				value={ value }
				onChange={ ( e ) => onChange( e.target.value ) }
				rows={ rows }
				{ ...props }
			/>
		</div>
	),
	PanelRow: ( { children } ) => (
		<div data-testid="panel-row">{ children }</div>
	),
	Spinner: () => <div data-testid="spinner">Loading...</div>,
} ) );

jest.mock( '@wordpress/i18n', () => ( {
	__: ( text ) => text,
} ) );

describe( 'PreviewPanel Component', () => {
	const mockContent = {
		seo_title: 'Test SEO Title',
		seo_description:
			'This is a test SEO description that is between 140 and 160 characters long.',
		focus_keyword: 'test keyword',
		og_title: 'Test OG Title',
		og_description:
			'This is a test OG description that is between 100 and 200 characters long for social media sharing.',
		twitter_title: 'Test Twitter Title',
		twitter_description: 'Test Twitter description for social media.',
		direct_answer:
			'This is a direct answer that should be between 300 and 450 characters long. It provides a concise answer to the main question about the topic. This answer is designed to be displayed in Google AI Overviews and should be informative and well-structured. It should cover the main points of the article in a clear and concise manner.',
		schema_type: 'Article',
		image_url: 'http://example.com/image.jpg',
		provider: 'Gemini',
	};

	const mockOnApply = jest.fn();
	const mockOnCancel = jest.fn();

	beforeEach( () => {
		jest.clearAllMocks();
	} );

	describe( 'Requirement 8.1-8.2: Display generated content', () => {
		it( 'should render preview panel with all fields', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			expect(
				screen.getByText( 'Preview Generated Content' )
			).toBeInTheDocument();
			expect( screen.getByText( 'SEO Title' ) ).toBeInTheDocument();
			expect( screen.getByText( 'SEO Description' ) ).toBeInTheDocument();
			expect( screen.getByText( 'Focus Keyword' ) ).toBeInTheDocument();
		} );

		it( 'should display generated image if available', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const image = screen.getByAltText( 'Generated featured image' );
			expect( image ).toBeInTheDocument();
			expect( image ).toHaveAttribute(
				'src',
				'http://example.com/image.jpg'
			);
		} );

		it( 'should not display image section if no image URL', () => {
			const contentWithoutImage = { ...mockContent };
			delete contentWithoutImage.image_url;

			render(
				<PreviewPanel
					content={ contentWithoutImage }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			expect(
				screen.queryByAltText( 'Generated featured image' )
			).not.toBeInTheDocument();
		} );

		it( 'should display provider information', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="OpenAI"
				/>
			);

			expect( screen.getByText( /Generated by:/ ) ).toBeInTheDocument();
			expect( screen.getByText( 'OpenAI' ) ).toBeInTheDocument();
		} );
	} );

	describe( 'Requirement 8.3-8.4: Character counts and limits', () => {
		it( 'should display character count for each field', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			// Check for character counts
			const charCounts = screen.getAllByRole( 'status' );
			expect( charCounts.length ).toBeGreaterThan( 0 );
		} );

		it( 'should highlight fields exceeding maximum length', () => {
			const contentWithLongTitle = {
				...mockContent,
				seo_title:
					'This is a very long SEO title that exceeds the maximum allowed length of 60 characters',
			};

			render(
				<PreviewPanel
					content={ contentWithLongTitle }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const warningMessages = screen.getAllByText(
				'Exceeds recommended length'
			);
			expect( warningMessages.length ).toBeGreaterThan( 0 );
		} );

		it( 'should highlight fields below minimum length', () => {
			const contentWithShortDescription = {
				...mockContent,
				seo_description: 'Too short',
			};

			render(
				<PreviewPanel
					content={ contentWithShortDescription }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const warningMessages = screen.getAllByText(
				'Exceeds recommended length'
			);
			expect( warningMessages.length ).toBeGreaterThan( 0 );
		} );

		it( 'should display minimum and maximum character limits in help text', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			// Check that fields are rendered with labels that indicate constraints
			expect( screen.getByText( 'SEO Title' ) ).toBeInTheDocument();
			expect( screen.getByText( 'SEO Description' ) ).toBeInTheDocument();
			expect( screen.getByText( 'Focus Keyword' ) ).toBeInTheDocument();
		} );
	} );

	describe( 'Requirement 8.6: Editable fields', () => {
		it( 'should allow editing of field values', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const titleInput = screen.getByDisplayValue( 'Test SEO Title' );
			fireEvent.change( titleInput, {
				target: { value: 'Updated Title' },
			} );

			expect( titleInput.value ).toBe( 'Updated Title' );
		} );

		it( 'should allow editing of textarea fields', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const descriptionTextarea = screen.getByDisplayValue(
				mockContent.seo_description
			);
			fireEvent.change( descriptionTextarea, {
				target: { value: 'Updated description' },
			} );

			expect( descriptionTextarea.value ).toBe( 'Updated description' );
		} );

		it( 'should pass edited content to onApply callback', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const titleInput = screen.getByDisplayValue( 'Test SEO Title' );
			fireEvent.change( titleInput, {
				target: { value: 'Updated Title' },
			} );

			fireEvent.click( screen.getByText( 'Apply to Fields' ) );

			expect( mockOnApply ).toHaveBeenCalledWith(
				expect.objectContaining( {
					seo_title: 'Updated Title',
				} )
			);
		} );
	} );

	describe( 'Requirement 8.7: Apply functionality', () => {
		it( 'should call onApply when Apply button is clicked', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			fireEvent.click( screen.getByText( 'Apply to Fields' ) );

			expect( mockOnApply ).toHaveBeenCalledWith( mockContent );
		} );

		it( 'should call onCancel when Cancel button is clicked', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			fireEvent.click( screen.getByText( 'Cancel' ) );

			expect( mockOnCancel ).toHaveBeenCalled();
		} );

		it( 'should disable buttons when isApplying is true', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ true }
					provider="Gemini"
				/>
			);

			expect( screen.getByText( 'Applying…' ) ).toBeDisabled();
			expect( screen.getByText( 'Cancel' ) ).toBeDisabled();
		} );

		it( 'should show loading spinner when isApplying is true', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ true }
					provider="Gemini"
				/>
			);

			expect( screen.getByTestId( 'spinner' ) ).toBeInTheDocument();
		} );

		it( 'should show "Applying…" text when isApplying is true', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ true }
					provider="Gemini"
				/>
			);

			expect( screen.getByText( 'Applying…' ) ).toBeInTheDocument();
		} );
	} );

	describe( 'Requirement 34.1-34.6: Accessibility features', () => {
		it( 'should have ARIA labels on all buttons', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const applyButton = screen.getByText( 'Apply to Fields' );
			expect( applyButton ).toHaveAttribute( 'aria-label' );
			expect( applyButton.getAttribute( 'aria-label' ) ).toContain(
				'Apply'
			);

			const cancelButton = screen.getByText( 'Cancel' );
			expect( cancelButton ).toHaveAttribute( 'aria-label' );
		} );

		it( 'should have proper label associations with form controls', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const titleLabel = screen.getByText( 'SEO Title' );
			expect( titleLabel ).toBeInTheDocument();

			const titleInput = screen.getByDisplayValue( 'Test SEO Title' );
			expect( titleInput ).toHaveAttribute( 'id' );
		} );

		it( 'should have ARIA descriptions for character counters', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const titleInput = screen.getByDisplayValue( 'Test SEO Title' );
			expect( titleInput ).toHaveAttribute( 'aria-describedby' );
		} );

		it( 'should have role="region" on preview panel', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const previewPanel = screen.getByRole( 'region' );
			expect( previewPanel ).toBeInTheDocument();
			expect( previewPanel ).toHaveAttribute( 'aria-label' );
		} );

		it( 'should have role="group" on fields container', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const fieldsGroup = screen.getByRole( 'group' );
			expect( fieldsGroup ).toBeInTheDocument();
			expect( fieldsGroup ).toHaveAttribute( 'aria-label' );
		} );

		it( 'should have role="status" on character count', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const statusElements = screen.getAllByRole( 'status' );
			expect( statusElements.length ).toBeGreaterThan( 0 );
		} );

		it( 'should have role="alert" on warning messages', () => {
			const contentWithLongTitle = {
				...mockContent,
				seo_title:
					'This is a very long SEO title that exceeds the maximum allowed length of 60 characters',
			};

			render(
				<PreviewPanel
					content={ contentWithLongTitle }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			const alertElements = screen.getAllByRole( 'alert' );
			expect( alertElements.length ).toBeGreaterThan( 0 );
		} );

		it( 'should set aria-busy on apply button when applying', () => {
			render(
				<PreviewPanel
					content={ mockContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ true }
					provider="Gemini"
				/>
			);

			const applyButton = screen.getByText( 'Applying…' );
			expect( applyButton ).toHaveAttribute( 'aria-busy', 'true' );
		} );
	} );

	describe( 'Edge cases', () => {
		it( 'should handle empty content gracefully', () => {
			const emptyContent = {
				seo_title: '',
				seo_description: '',
				focus_keyword: '',
				og_title: '',
				og_description: '',
				twitter_title: '',
				twitter_description: '',
				direct_answer: '',
				schema_type: '',
			};

			render(
				<PreviewPanel
					content={ emptyContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			expect(
				screen.getByText( 'Preview Generated Content' )
			).toBeInTheDocument();
		} );

		it( 'should handle content with special characters', () => {
			const contentWithSpecialChars = {
				...mockContent,
				seo_title: 'Test & "Special" <Characters>',
			};

			render(
				<PreviewPanel
					content={ contentWithSpecialChars }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			expect(
				screen.getByDisplayValue( 'Test & "Special" <Characters>' )
			).toBeInTheDocument();
		} );

		it( 'should handle very long content', () => {
			const longContent = {
				...mockContent,
				direct_answer: 'A'.repeat( 500 ),
			};

			render(
				<PreviewPanel
					content={ longContent }
					onApply={ mockOnApply }
					onCancel={ mockOnCancel }
					isApplying={ false }
					provider="Gemini"
				/>
			);

			expect(
				screen.getByDisplayValue( 'A'.repeat( 500 ) )
			).toBeInTheDocument();
		} );
	} );
} );
